parameters:
  assignments2:
        dev: 
          name: dev_self_training
          color: 468847
          
        sm:
          name: SM
          color: b94a48
         
        devsm:
          name: dev_sm_training
          color: 3A87AD
         
        po:
          name: PO
          color: 999999
     
  types2:
        meeting:
            name: meeting
            icon: icons/users.png
        mail:
            name: mail
            icon: icons/envelop.png
        default:
            name: default
            icon: icons/spinner.png
        document:
            name: document
            icon: icons/paperclip.png
        
  days2:
    day_1:
      name: day_1 21.02.2013
      tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png 
            type: meeting
            info: pavel/standUpUser.html.twig
            
          task2:
            name: 7.5h - Meetic website discovery
            assign: dev
            icon: icons/users.png 
            type: meeting
            info: pavel/meetic-questions.html.twig
            
          task3:
            name: Create Meetic access requests
            assign: sm
            type: meeting
            info: pavel/meetic-access-request.html.twig
            
          task4:
            name: Add new team member to email groups
            assign: sm
            type: meeting
            info: pavel/pentalog-email-groups.html.twig
            
          task5:
            name: Add new team member to VPN tunnel
            assign: sm
            type: meeting
            info: pavel/pentalog-vpn-tunnel.html.twig
            
          task6:
            name: Ilius Wiki access request
            assign: sm
            type: meeting
            info: pavel/wiki-ilius.html.twig
                
                    
    day_2:
      name: day_2 22.02.2013
      tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/standUpUserDay2.html.twig

          task2:
            name: 5h - Study TEAM documents
            assign: dev
            icon: icons/download.png
            type: document
            info: pavel/documentation.html.twig
            attachments:
              animated-browser: training/Animated-tabs99.pdf
              specifiications-refonte-signup: training/Specifications-RefonteSignup-v0.6.pdf
              photo-uploader: training/Specs-PhotoUploaderNG-v1.0.pdf
              photo-size: training/Specs-Photosizeoptimization-v1.8.pdf
              profile-page-design: training/Specs-Profilepagedesignreview-v0.6.pdf
              
          task3:
            name: 2.5h - Workshop Release process & project specific tools
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/release-process-and-tools.html.twig
     
    day_3:
      name: day_3 25.02.2013
      tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-git.html.twig
             
          task2:
            name: 5h - GIT-commands
            assign: dev
            icon: icons/users.png
            type: meeting
            info: pavel/git.html.twig
            attachments:
              git-commands: training/GITcommands.docx
              SSH: training/Installing-ssh.pdf
 
    day_4:
       name: day_4 26.02.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-newDoc.html.twig
 
          task2:
            name: 4h - Study General Project Documentation
            assign: dev 
            info: pavel/general-documentation.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              Jira: training/jira.pdf
              Mantis Release: training/Mantis_Release_Process.doc
              PHP5 best practices: training/BestPractices_PHP5.pdf
            
    day_5:
       name: day_5 27.02.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-supertracking.html.twig
 
          task2:
            name: 4h - Study General Project Documentation - SuperTracking
            assign: dev 
            info: pavel/supertracking-documentation.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              SuperTracking: training/En_Supertracking.pdf
              
          task3:
            name: 3.5h - Study Technic Project Documentation 
            assign: dev 
            info: pavel/technic-documentation.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              Glosaire: training/1_Glossaire.doc
              Coding Standards: training/2_meetic-coding-standards_v2.2.doc
              Best Practices: training/10_best_practices_en.doc
              CCS RULES ON V6: training/V6_CSS_cheat_sheet.pdf
              Comment installer Eclipse: training/3_Comment_installer_Eclipse.pdf
            
    day_6:
       name: day_6 28.02.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-technical.html.twig
 
          task2:
            name: 7.5h - Study Technical Project Documentation 
            assign: dev 
            info: pavel/technic-documentation2.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              Informations: training/4_informations_utiles.doc
              Architecture: training/5_archi.doc
              Module de liste: training/6a_mlist.pdf
              Listes Meetic: training/6b_mlist.pdf
              Framework listes: training/6c_framework_listes.ods
              YATS: training/7a_YATS.doc
              
    day_7:
       name: day_7 01.03.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-technical.html.twig
 
          task2:
            name: 7.5h - Study Technical Project Documentation 
            assign: dev 
            info: pavel/technic-documentation3.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              Cache: training/8_cache.doc
              Yats functions: training/7b_Les_nouvelles_fonctions_ajoutées_à_yats.doc
              Bases: training/9_bases_de_données_v1.0.doc
              Configuration Meetic: training/10a_Documentation_de_la_configuration_meetic.ods
              Bien commencer: training/Quelques_liens_pour_commencer.doc
              Meetic Photos: training/11_meetic_front_photos.doc
              Git: training/GIT.doc
              A-B testing: training/ABTesting_-_Introduction_US.ppt
              
    day_8:
       name: day_8 04.03.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-technical.html.twig
 
          task2:
            name: 7.5h - Study Technical Project Documentation 
            assign: dev 
            info: pavel/technic-documentation4.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              yats: training/Yats_c_extension_documentation.pdf
              Publio: training/PUBLIO_-_Présentation.ppt
              SSH: training/Installing_a_SSH_Server_for_GIT_-_Win7.odt
              SCpublic: training/SCpublic_CrossSelling_Doc_Technique_-_Wiki_Meetic.pdf
              Photo uploader: training/Technical_-_Photo_Upload_Component_-_v0.4.2.pdf
              OBO: training/OBO_Regular_-_Refonte_de_l'Admin_-_v1.0.doc          
              
    day_9:
       name: day_9 05.03.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-discovery.html.twig
 
          task2:
            name: 3h - Installation 
            assign: dev 
            info: pavel/install.html.twig
            icon: icons/paperclip.png
            type: document
            
          task3:
            name: 0.5h - Meeting
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/Meetic-discovery.html.twig
            
          task4:
            name: 2h - Clone master to DEV-NG
            assign: dev
            icon: icons/users.png
            type: document
            info: pavel/dev.html.twig
            
          task5:
            name: 2h - Sprint-planing
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/sprint-plann.html.twig
            
            
    day_10:
       name: day_10 06.03.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-discovery2.html.twig
 
          task2:
            name: 7.5h - discover website 
            assign: dev 
            info: pavel/website-study.html.twig
            icon: icons/paperclip.png
            type: document
            
            
    day_11:
       name: day_11 07.03.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-discovery2.html.twig
 
          task2:
            name: 7.5h - GIT 
            assign: dev 
            info: pavel/website-study-git.html.twig
            icon: icons/paperclip.png
            type: document
            
     
    day_12:
       name: day_12 08.03.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-discovery2.html.twig
 
          task2:
            name: 5.5h - GIT 
            assign: dev 
            info: pavel/website-study-git.html.twig
            icon: icons/paperclip.png
            type: document
            
          task3:
            name: 2h - Pentalog tests 
            assign: dev 
            info: pavel/pentalog.html.twig
            icon: icons/paperclip.png
            type: document
            
            
    day_13:
       name: day_13 11.03.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/user-story.html.twig
 
          task2:
            name: 7.5h - user story 
            assign: dev 
            info: pavel/website-study-git.html.twig
            icon: icons/paperclip.png
            type: document
            
         
            
         
            
            

            
          

  