parameters:
  assignments2:
        dev: 
          name: dev_self_training
          color: 468847
          
        sm:
          name: SM
          color: b94a48
         
        devsm:
          name: dev_sm_training
          color: 3A87AD
         
        po:
          name: PO
          color: 999999
     
  types2:
        meeting:
            name: meeting
            icon: icons/users.png
        mail:
            name: mail
            icon: icons/envelop.png
        default:
            name: default
            icon: icons/spinner.png
        document:
            name: document
            icon: icons/paperclip.png
        
  days2:
    day_1:
      name: day_1 21.02.2013
      tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png 
            type: meeting
            info: pavel/standUpUser.html.twig
            
          task2:
            name: 7.5h - Meetic website discovery
            assign: dev
            icon: icons/users.png 
            type: meeting
            info: pavel/meetic-questions.html.twig
            
          task3:
            name: Create Meetic access requests
            assign: sm
            type: meeting
            info: pavel/meetic-access-request.html.twig
            
          task4:
            name: Add new team member to email groups
            assign: sm
            type: meeting
            info: pavel/pentalog-email-groups.html.twig
            
          task5:
            name: Add new team member to VPN tunnel
            assign: sm
            type: meeting
            info: pavel/pentalog-vpn-tunnel.html.twig
            
          task6:
            name: Ilius Wiki access request
            assign: sm
            type: meeting
            info: pavel/wiki-ilius.html.twig
                
                    
    day_2:
      name: day_2 22.02.2013
      tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/standUpUserDay2.html.twig

          task2:
            name: 5h - Study TEAM documents
            assign: dev
            icon: icons/download.png
            type: document
            info: pavel/documentation.html.twig
            attachments:
              animated-browser: Animated-tabs99.pdf
              specifiications-refonte-signup: Specifications-RefonteSignup-v0.6.pdf
              photo-uploader: Specs-PhotoUploaderNG-v1.0.pdf
              photo-size: Specs-Photosizeoptimization-v1.8.pdf
              profile-page-design: Specs-Profilepagedesignreview-v0.6.pdf
              
          task3:
            name: 2.5h - Workshop Release process & project specific tools
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/release-process-and-tools.html.twig
     
    day_3:
      name: day_3 25.02.2013
      tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-git.html.twig
             
          task2:
            name: 5h - GIT-commands
            assign: dev
            icon: icons/users.png
            type: meeting
            info: pavel/git.html.twig
            attachments:
              git-commands: GITcommands.docx
              SSH: Installing-ssh.pdf
 
    day_4:
       name: day_4 26.02.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-newDoc.html.twig
 
          task2:
            name: 4h - Study General Project Documentation
            assign: dev 
            info: pavel/general-documentation.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              Jira: jira.pdf
              Mantis Release: Mantis_Release_Process.doc
              PHP5 best practices: BestPractices_PHP5.pdf
            
    day_5:
       name: day_5 27.02.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-supertracking.html.twig
 
          task2:
            name: 4h - Study General Project Documentation - SuperTracking
            assign: dev 
            info: pavel/supertracking-documentation.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              SuperTracking: En_Supertracking.pdf
              
          task3:
            name: 3.5h - Study Technic Project Documentation 
            assign: dev 
            info: pavel/technic-documentation.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              Glosaire: 1_Glosaire.doc
              Coding Standards: 2_meetic-coding-standards_v2.2.doc
              Best Practices: 10_best_practices_en.doc
              CCS RULES ON V6: V6_CSS_cheat_sheet.pdf
              Comment installer Eclipse: 3_Comment_installer_Eclipse.pdf
            
    day_6:
       name: day_6 28.02.2013
       tasks:
          task1:
            name: 0.5h - Stand up
            assign: devsm
            icon: icons/users.png
            type: meeting
            info: pavel/stand-up-technical.html.twig
 
          task2:
            name: 7.5h - Study Technical Project Documentation 
            assign: dev 
            info: pavel/technic-documentation2.html.twig
            icon: icons/paperclip.png
            type: document
            attachments:
              Informations: 4_informations_utiles.doc
              Architecture: 5_archi.doc
              Module de liste: 6a_mlist.pdf
              Listes Meetic: 6b_mlist.pdf
              Framework listes: 6c_framework_listes.ods
              YATS: 7a_YATS.doc
              
          
              
              

  