parameters:
  assignments:
        release: 
          name: RELEASE
          color: 468847
          
        sm:
          name: SM
          color: 999999
         
        test:
          name: TEST
          color: 3A87AD
         
        po:
          name: PO
          color: b94a48
     
  types:
        meeting:
            name: meeting
            icon: icons/users.png
        mail:
            name: mail
            icon: icons/envelop.png
        default:
            name: default
            icon: icons/spinner.png
        document:
            name: document
            icon: icons/paperclip.png
        
  days:
    day_1:
      name: day1
      tasks:
          task1:
            name: Stand up
            assign: sm
            icon: icons/users.png 
            type: meeting
            info: template/standUp.html.twig
            attachments:
              file kfnds: rest.jpg
              file2s: day1/curl-commands.txt
              fileds kfnds: rest.jpg
              filesd2: day1/curl-commands.txt
              fildse kfnds: rest.jpg
              fildsfge2: day1/curl-commands.txt
              filgfe kfnds: rest.jpg
              filgge2: day1/curl-commands.txt
              
          task2:
            name: Daily report
            assign: sm
            icon: icons/envelop.png
            type: mail
            info: details.html.twig
            attachments:
              fa: rest.jpg
              fsfsfs: curl-commands.txt
            

          task3:
            name: MEP merged projects
            assign: release
            url: lolhost2
            icon: icons/upload2.png
            type: document

          task4:
            name: Merge prev project on release branch
            assign: sm
            url: lalalla
            icon: icons/fullscreen-exit-alt.png
            type: default

          task5:
            name: STO/2
            assign: test
            url: aaaaaa
            icon: icons/envelop.png
            type: mail
        
        
        
    day_2:
      name: day2
      tasks:
          task1:
            name: Stand up
            assign: sm
            url: urlsss
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: sm
            url: urllsss
            icon: icons/envelop.png
            type: mail

          task3:
            name: OOO PM
            assign: sm
            url: urlsss
            icon: icons/users.png
            type: meeting

          task4:
            name: Post merge testing
            assign: release
            url: urlssssss
            icon: icons/search2.png
            type: default

        
        
    day_3:
      name: day3
      tasks:
          task1:
            name: Stand up
            assign: sm
            url: alalla
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: sm
            url: alallala
            icon: icons/envelop.png
            type: mail

          task3:
            name: Scrum of Scrum
            assign: sm
            url: alklkl
            icon: icons/users.png
            type: meeting

          task4:
            name: Test report doc
            assign: test
            url: restttt
            icon: icons/paperclip.png
            type: default

          task5:
            name: Test runs doc
            assign: test
            url: ahjsdhjhdsj
            icon: icons/paperclip.png
            type: default

          task6:
            name: Test report & runs
            assign: test
            url: akjkjk
            icon: icons/envelop.png
            type: mail

          task7:
            name: Export merged projects in recette
            assign: release
            url: lklklklds
            icon: icons/upload2.png
            type: default



    day_4:
       name: day4
       tasks:
          task1:
            name: Stand up
            assign: sm
            url: alalla
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: sm
            url: alallala
            icon: icons/envelop.png
            type: mail

          task3:
            name: Prepare op com support
            assign: sm
            url: alklkl
            icon: icons/paperclip.png
            type: default

          task4:
            name: Operational committee
            assign: sm
            url: restsddttt
            icon: icons/users.png
            type: meeting

          task5:
            name: Send op com followup
            assign: sm
            url: ahjsdsshjhdsj
            icon: icons/envelop.png
            type: mail

          task6:
            name: Add op com to wiki & sharepoint
            assign: sm
            url: akjkssjk
            icon: icons/spinner.png
            type: default

          task7:
            name: Testers meeting
            assign: test
            url: lbbbbs
            icon: icons/users.png
            type: meeting

          task8:
            name: Technical status
            assign: sm
            url: lkllds
            icon: icons/users.png
            type: meeting

          task9:
            name: SM meeting
            assign: sm
            url: lklklkddsalds
            icon: icons/users.png
            type: meeting



    day_5:
       name: day5
       tasks:
          task1:
            name: Stand up
            assign: sm
            url: alallafff
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: sm
            url: alalffff
            icon: icons/envelop.png
            type : mail



    day_6:
       name: day6
       tasks:
          task1:
            name: Stand up
            assign: sm
            url: ala444lla
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: sm
            url: alal444lala
            icon: icons/envelop.png
            type: mail

          task3:
            name: test plan doc
            assign: test
            url: alklkl
            icon: icons/paperclip.png
            type: default

          task4:
            name: Test cases doc
            assign: test
            url: restsddttt
            icon: icons/paperclip.png
            type: default

          task5:
            name: Test plan & cases
            assign: test
            url: restsddttt
            icon: icons/envelop.png
            type: mail



    day_7:
       name: day7
       tasks:
          task1:
            name: Stand up
            assign: sm
            url: ala444lla
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: sm
            url: alal
            icon: icons/envelop.png
            type: mail

          task3:
            name: OOO PM
            assign: sm
            url: alklk
            icon: icons/users.png
            type: meeting
            
          task4:
            name: Export Mantis fixes on recette
            assign: release
            url: alklk
            icon: icons/upload2.png
            type: default



    day_8:
       name: day8
       tasks:
          task1:
            name: Stand up
            assign: sm
            url: ala444lla
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: sm
            url: alal
            icon: icons/envelop.png
            type: mail

          task3:
            name: OOO Team
            assign: sm
            url: alklk
            icon: icons/users.png
            type: meeting
            
          task4:
            name: Specs - From PO
            assign: po
            url: alklk
            icon: icons/download.png
            type: default
    
    
    day_9:
       name: day9
       tasks:
          task1:
            name: Stand up
            assign: sm
            url: ala444la
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: sm
            url: a444lala
            icon: icons/envelop.png
            type : mail

          task3:
            name: Demo invitation
            assign: sm
            url: alklwwwkl
            icon: icons/envelop.png
            type : mail

          task4:
            name: Analize next sprint specs
            assign: sm
            url: rett
            icon: icons/book-alt2.png
            type: default
          
          task5:
            name: Prepare op com support
            assign: sm
            url: alklkl
            icon: icons/paperclip.png
            type: default

          task6:
            name: Operational committee
            assign: sm
            url: restsddttt
            icon: icons/users.png
            type: meeting

          task7:
            name: Send op com followup
            assign: sm
            url: ahjsdsshjhdsj
            icon: icons/envelop.png
            type : mail

          task8:
            name: Add op com to wiki & sharepoint
            assign: sm
            url: akjkssjk
            icon : icons/spinner.png
            type: default

          task9:
            name: Testers meeting
            assign: test
            url: lbbbbs
            icon: icons/users.png
            type: meeting

          task10:
            name: Technical status
            assign: sm
            url: lkllds
            icon: icons/users.png
            type: meeting

          task11:
            name: SM meeting
            assign: sm
            url: lklklkddsalds
            icon: icons/users.png
            type: meeting
         
         
         
    day_10:
       name: day10
       tasks:
          task1:
            name: Stand up
            assign: sm
            url: ala444la
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: sm
            url: a444dfdla
            icon: icons/envelop.png
            type: mail

          task3:
            name: Sprint demo
            assign: sm
            url: alklwwwkl
            icon: icons/users.png
            type: meeting

          task4:
            name: Sprint retrospective
            assign: sm
            url: rett
            icon: icons/users.png
            type: meeting

          task5:
            name: Sprint planning
            assign: sm
            url: redfdtt
            icon: icons/users.png
            type: meeting

          task6:
            name: Sprint planning
            assign: sm
            url: refrrtt
            icon: icons/envelop.png
            type: mail

          task7:
            name: SLR  to PM / 2
            assign: sm
            url: retdast
            icon: icons/paperclip.png
            type: default
