parameters:
  assignments:
        done: 
          name: done
          color: 468847
          
        claudia:
          name: claudia
          color: 999999
         
        tudor:
          name: tudor
          color: 3A87AD
         
        tiby:
          name: tiby
          color: b94a48
     
  types:
        meeting:
            name: meeting
            icon: icons/users.png
        mail:
            name: mail
            icon: icons/envelop.png
        default:
            name: default
            icon: icons/spinner.png
        document:
            name: document
            icon: icons/paperclip.png
        
  days:
    day_1:
      name: day1
      tasks:
          task1:
            name: Stand up
            assign: tiby
            icon: icons/users.png 
            type: meeting
            info: template/standUp.html.twig
            attachments:
              file kfnds: rest.jpg 
              
          task2:
            name: Daily report
            assign: done
            icon: icons/envelop.png
            type: mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft
            

          task3:
            name: MEP merged projects
            assign: tiby
            info: template/mepMergeProject.html.twig
            icon: icons/upload2.png
            type: document

          task4:
            name: Merge prev project on release branch
            assign: tiby
            info: template/mergePrevProject.html.twig
            icon: icons/fullscreen-exit-alt.png
            type: default

          task5:
            name: STO/2
            assign: tudor
            info: template/sto.html.twig
            icon: icons/envelop.png
            type: mail
        
        
    day_2:
      name: day2
      tasks:
          task1:
            name: Stand up
            assign: tiby
            info: template/standUp.html.twig
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: done
            icon: icons/envelop.png
            type: mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft

          task3:
            name: OOO PM
            assign: tiby
            info: template/oooPM.html.twig
            icon: icons/users.png
            type: meeting

          task4:
            name: Post merge testing
            assign: tudor
            info: template/postMergeTesting.html.twig
            icon: icons/search2.png
            type: default

        
        
    day_3:
      name: day3
      tasks:
          task1:
            name: Stand up
            assign: tiby
            info: template/standUp.html.twig
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: done
            info: template/dailyReport.html.twig
            icon: icons/envelop.png
            type: mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft

          task3:
            name: Scrum of Scrum
            assign: tiby
            info: template/scrumOfScrum.html.twig
            icon: icons/users.png
            type: meeting

          task4:
            name: Test report doc
            assign: claudia
            info: template/testReportDoc.html.twig
            icon: icons/paperclip.png
            type: default

          task5:
            name: Test runs doc
            assign: claudia
            info: template/testRunDoc.html.twig
            icon: icons/paperclip.png
            type: default

          task6:
            name: Test report & runs
            assign: claudia
            info: template/testReportAndRuns.html.twig
            icon: icons/envelop.png
            type: mail

          task7:
            name: Export merged projects in recette
            assign: tudor
            info: template/exportProjectInRecette.html.twig
            icon: icons/upload2.png
            type: default



    day_4:
       name: day4
       tasks:
          task1:
            name: Stand up
            assign: tiby
            info: template/standUp.html.twig
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: done
            icon: icons/envelop.png
            type: mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft

          task3:
            name: Prepare op com support
            assign: tiby
            info: template/prepareOpComSupport.html.twig
            icon: icons/paperclip.png
            type: default

          task4:
            name: Operational committee
            assign: tudor
            info: template/operationalComittee.html.twig
            icon: icons/users.png
            type: meeting

          task5:
            name: Send op com followup
            assign: tiby
            info: template/sendOpComFollowup.html.twig
            icon: icons/envelop.png
            type: mail

          task6:
            name: Add op com to wiki & sharepoint
            assign: tiby
            info: template/addOpComWikiSharepoint.html.twig
            icon: icons/spinner.png
            type: default

          task7:
            name: Testers meeting
            assign: tiby
            info: template/testersMeeting.html.twig
            icon: icons/users.png
            type: meeting

          task8:
            name: Technical status
            assign: tudor
            info: template/technicalStatus.html.twig
            icon: icons/users.png
            type: meeting

          task9:
            name: SM meeting
            assign: tudor
            info: template/smMeeting.html.twig
            icon: icons/users.png
            type: meeting



    day_5:
       name: day5
       tasks:
          task1:
            name: Stand up
            assign: tiby
            info: template/standUp.html.twig
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: done
            icon: icons/envelop.png
            type: mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft



    day_6:
       name: day6
       tasks:
          task1:
            name: Stand up
            assign: tiby
            info: template/standUp.html.twig
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: done
            icon: icons/envelop.png
            type: mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft

          task3:
            name: Test plan doc
            assign: claudia
            info: template/testPlanDoc.html.twig
            icon: icons/paperclip.png
            type: default

          task4:
            name: Test cases doc
            assign: claudia
            info: template/testCasesDoc.html.twig
            icon: icons/paperclip.png
            type: default

          task5:
            name: Test plan & cases
            assign: claudia
            info: template/testPlanAndCases.html.twig
            icon: icons/envelop.png
            type: mail



    day_7:
       name: day7
       tasks:
          task1:
            name: Stand up
            assign: tiby
            info: template/standUp.html.twig
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: done
            icon: icons/envelop.png
            type: mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft

          task3:
            name: OOO PM
            assign: tiby
            info: template/oooPM.html.twig
            icon: icons/users.png
            type: meeting
            
          task4:
            name: Export Mantis fixes on recette
            assign: tiby
            info: template/exportMantisFixesRecette.html.twig
            icon: icons/upload2.png
            type: default



    day_8:
       name: day8
       tasks:
          task1:
            name: Stand up
            assign: tiby
            info: template/standUp.html.twig
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: done
            icon: icons/envelop.png
            type: mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft

          task3:
            name: OOO Team
            assign: tiby
            info: template/oooTeam.html.twig
            icon: icons/users.png
            type: meeting
            
          task4:
            name: Specs - From PO
            assign: tudor
            url: template/specsPO.html.twig
            icon: icons/download.png
            type: default
    
    
    day_9:
       name: day9
       tasks:
          task1:
            name: Stand up
            assign: tiby
            info: template/standUp.html.twig
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: done
            icon: icons/envelop.png
            type: mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft

          task3:
            name: Demo invitation
            assign: tudor
            info: template/demoInvitation.html.twig
            icon: icons/envelop.png
            type : mail

          task4:
            name: Analize next sprint specs
            assign: tudor
            info: template/analizeNextSprintSpecs.html.twig
            icon: icons/book-alt2.png
            type: default
          
          task5:
            name: Prepare op com support
            assign: tiby
            info: template/prepareOpComSupport.html.twig
            icon: icons/paperclip.png
            type: default

          task6:
            name: Operational committee
            assign: tudor
            info: template/operationalComittee.html.twig
            icon: icons/users.png
            type: meeting

          task7:
            name: Send op com followup
            assign: tiby
            info: template/sendOpComFollowup.html.twig
            icon: icons/envelop.png
            type : mail

          task8:
            name: Add op com to wiki & sharepoint
            assign: tiby
            info: template/addOpComWikiSharepoint.html.twig
            icon : icons/spinner.png
            type: default

          task9:
            name: Testers meeting
            assign: claudia
            info: template/testersMeeting.html.twig
            icon: icons/users.png
            type: meeting

          task10:
            name: Technical status
            assign: tudor
            info: template/technicalStatus.html.twig
            icon: icons/users.png
            type: meeting

          task11:
            name: SM meeting
            assign: tudor
            info: template/smMeeting.html.twig
            icon: icons/users.png
            type: meeting
         
         
         
    day_10:
       name: day10
       tasks:
          task1:
            name: Stand up
            assign: tiby
            info: template/standUp.html.twig
            icon: icons/users.png
            type: meeting

          task2:
            name: Daily report
            assign: done
            icon: icons/envelop.png
            type : mail
            info: template/dailyReport.html.twig
            attachments:
              DOWNLOAD template: timeline/daily_report_email_template.oft

          task3:
            name: Sprint demo
            assign: tiby
            info: template/sprintDemo.html.twig
            icon: icons/users.png
            type: meeting

          task4:
            name: Sprint retrospective
            assign: tiby
            info: template/sprintRetro.html.twig
            icon: icons/users.png
            type: meeting

          task5:
            name: Sprint planning
            assign: tiby
            info: template/sprintPlanning.html.twig
            icon: icons/users.png
            type: meeting

          task6:
            name: Sprint planning
            assign: tiby
            info: template/sprintPlanningMail.html.twig
            icon: icons/envelop.png
            type: mail

          task7:
            name: SLR  to PM / 2
            assign: tudor
            info: template/srlToPm.html.twig
            icon: icons/paperclip.png
            type: default
