root:
    pattern:  /
    defaults: { _controller: mr1Mr1Bundle:Page:TimeLine }
    
timeline:
    pattern:  /timeline
    defaults: { _controller: mr1Mr1Bundle:Page:TimeLine }
    
new_timeline:
    pattern:  /newtimeline
    defaults: { _controller: mr1Mr1Bundle:Page:NewTimeLine }
    
ajax_call:
    pattern: /ajax
    defaults: { _controller: mr1Mr1Bundle:Page:Ajax }
    requirements:
        _method:  POST
        
get_attachment:
    pattern: /download/{filename}
    defaults: { _controller: mr1Mr1Bundle:Page:download }
    requirements:
         filename: ".+"
    

